--- #mongodb install
- hosts: localhost
  become: yes
  tasks:
  - name: Import the public key used by the package management system
    apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=7F0CEB10 state=present
  - name: Create a list file for MongoDB
    raw: echo "deb [ arch=amd64 ] http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.4.list
  - name: install mongodb
    apt: pkg=mongodb-org state=latest update_cache=yes
    notify:
    - restart mongodb
  handlers:
    - name: restart mongodb
      service: name=mongod state=restarted

